export const clientColumns = [
  { field: "id", headerName: "ID", width: 70 },
  {
    field: "name",
    headerName: "Imię",
    width: 120,
  },
  {
    field: "surname",
    headerName: "Nazwisko",
    width: 130,
  },

  {
    field: "street",
    headerName: "Ulica",
    width: 130,
  },

  {
    field: "number",
    headerName: "Numer",
    width: 100,
  },

  {
    field: "postcode",
    headerName: "Kod",
    width: 100,
  },

  {
    field: "city",
    headerName: "Miejscowość",
    width: 130,
  },

  {
    field: "phone",
    headerName: "Telefon",
    width: 180,
  },

  {
    field: "email",
    headerName: "Email",
    width: 350,
  },
];

//temporary data
export const clientRows = [
  {
    id: 1,
    name: "Jan",
    surname: "Kowalski",
    street: "Krótka",
    number: "12",
    postcode: "15-123",
    city: "Białystok",
    phone: "+48799361513",
    email: "janekk@wp.pl",
  },
  {
    id: 2,
    name: "Krzysztof",
    surname: "Kwiatkowski",
    street: "Zielona",
    number: "32/2",
    postcode: "54-234",
    city: "Wrocław",
    phone: "+48533728482",
    email: "kkwiatkowski@interia.pl",
  },
  {
    id: 3,
    name: "Roman",
    surname: "Szewczyk",
    street: "Zwycięstwa",
    number: "345",
    postcode: "40-223",
    city: "Katowice",
    phone: "+48692753333",
    email: "romanek23@o2.pl",
  },
  {
    id: 4,
    name: "Anna",
    surname: "Nowak",
    street: "Bajkowa",
    number: "17/10",
    postcode: "02-250",
    city: "Warszawa",
    phone: "+48799357578",
    email: "anna.nowak@gmail.com",
  },
  {
    id: 5,
    name: "Karol",
    surname: "Szymczak",
    street: "Chrobrego",
    number: "34",
    postcode: "70-253",
    city: "Szczecin",
    phone: "+48517223175",
    email: "karolszymczak@onet.pl",
  },
  {
    id: 6,
    name: "Edyta",
    surname: "Zając",
    street: "3-go Maja",
    number: "123",
    postcode: "00-125",
    city: "Warszawa",
    phone: "+48603888108",
    email: "edytazajac@gmail.com",
  },
  {
    id: 7,
    name: "Adam",
    surname: "Krzeszowski",
    street: "Sportowa",
    number: "34/8",
    postcode: "65-723",
    city: "Zielona Góra",
    phone: "+48579572744",
    email: "a.krzeszowski@gmail.com",
  },
  {
    id: 8,
    name: "Katarzyna",
    surname: "Olszewska",
    street: "Szkolna",
    number: "8",
    postcode: "80-054",
    city: "Gdańsk",
    phone: "+48668737185",
    email: "olszewska_kasia@wp.pl",
  },
  {
    id: 9,
    name: "Jacek",
    surname: "Rachwalski",
    street: "Polna",
    number: "25/1",
    postcode: "75-234",
    city: "Koszalin",
    phone: "+48514524752",
    email: "jacekr@gmail.com",
  },
  {
    id: 10,
    name: "Arkadiusz",
    surname: "Bąk",
    street: "Słoneczna",
    number: "15/3",
    postcode: "50-232",
    city: "Wrocław",
    phone: "+48695883277",
    email: "arakbak@wp.pl",
  },
  {
    id: 11,
    name: "Zenon",
    surname: "Maślak",
    street: "Lipowa",
    number: "14",
    postcode: "61-726",
    city: "Poznań",
    phone: "+48668747111",
    email: "zenonmaslak@interia.pl",
  },
];
