export let kanbanData = [
  {
    Id: "Zadanie 1",
    Title: "Zadanie - 29001",
    Status: "Do podjęcia",
    Opis: "Przygotowanie rozliczenia za poprzedni miesiąc.",
    Type: "Story",
    Priority: "Low",
    Estimate: 3.5,
    Przypisz: "Ewa Sikora",
  },
  {
    Id: "Zadanie 2",
    Title: "Zadanie - 29002",
    Status: "Wykonywane",
    Opis: "Wycena samochodu",
    Type: "Improvement",
    Priority: "Normal",
    Estimate: 6,
    Przypisz: "Anna Nowak",
  },
  {
    Id: "Zadanie 3",
    Title: "Zadanie - 29003",
    Status: "Do podjęcia",
    Opis: "Przygotowanie planów sprzedażowych oraz zakupowych.",
    Type: "Others",
    Priority: "Critical",
    Estimate: 5.5,
    Przypisz: "Jan Kowalski",
  },
  {
    Id: "Zadanie 4",
    Title: "Zadanie - 29004",
    Status: "Wykonywane",
    Opis: "Przygotowanie bilansu za ostatni kwartał.",
    Type: "Bug",
    Priority: "Critical",
    Estimate: 2.5,
    Przypisz: "Jan Kowalski",
  },
  {
    Id: "Zadanie 5",
    Title: "Zadanie - 29005",
    Status: "Do sprawdzenia",
    Opis: "Sprawdzenie samochodu po naprawie mechanicznej.",
    Type: "Bug",
    Priority: "Low",
    Estimate: "3.5",
    Przypisz: "Krzysztof Kwiatkowski",
  },
  {
    Id: "Zadanie 6",
    Title: "Zadanie - 29007",
    Status: "Sprawdzane",
    Opis: "Kontrola samochodu przed wydaniem",
    Type: "Improvement",
    Priority: "Low",
    Estimate: 1.5,
    Przypisz: "Jacek Traczyk",
  },
  {
    Id: "Zadanie 7",
    Title: "Zadanie - 29009",
    Status: "Do sprawdzenia",
    Opis: "Sprawdzenie poprawności naliczonych wynagrodzeń.",
    Type: "Bug",
    Priority: "Critical",
    Estimate: 1.5,
    Przypisz: "Ewa Sikora",
  },
  {
    Id: "Zadanie 8",
    Title: "Zadanie - 29010",
    Status: "Zakończone",
    Opis: "Przekazanie samochodu dla handlowca do wydania.",
    Type: "Story",
    Priority: "Low",
    Estimate: 5.5,
    Przypisz: "Adam Polak",
  },
  {
    Id: "Zadanie 9",
    Title: "Zadanie - 29011",
    Status: "Sprawdzane",
    Opis: "Sprawdzenie samochodu przed wydaniem.",
    Type: "Story",
    Priority: "High",
    Estimate: 1,
    Przypisz: "Krzysztof Kwiatkowski",
  },
  {
    Id: "Zadanie 10",
    Title: "Zadanie - 29015",
    Status: "Do podjęcia",
    Opis: "Zamówienie części zamiennych.",
    Type: "Story",
    Priority: "High",
    Estimate: 5.5,
    Przypisz: "Adam Polak",
  },
  {
    Id: "Zadanie 11",
    Title: "Zadanie - 29016",
    Status: "Wykonywane",
    Opis: "Przygotowanie ogłoszenia o pracę na stanowisko informatyka.",
    Priority: "Critical",
    Type: "Bug",
    Estimate: 2.5,
    Przypisz: "Jan Kowalski",
  },
  {
    Id: "Zadanie 12",
    Title: "Zadanie - 29017",
    Status: "Do sprawdzenia",
    Opis: "Dokumentacja sprzedażowa - sprawdzenie poprawności transakcji.",
    Type: "Story",
    Priority: "Normal",
    Estimate: "3.5",
    Przypisz: "Jan Kowalski",
  },
  {
    Id: "Zadanie 13",
    Title: "Zadanie - 29018",
    Status: "Zakończone",
    Opis: "Wydanie samochodu.",
    Type: "Story",
    Priority: "Critical",
    Estimate: 2,
    Przypisz: "Anna Nowak",
  },
  {
    Id: "Zadanie 14",
    Title: "Zadanie - 29019",
    Status: "Sprawdzane",
    Opis: "Kontrola samochodu przed wydaniem.",
    Type: "Story",
    Priority: "Low",
    Estimate: 1.5,
    Przypisz: "Adam Polak",
  },
  {
    Id: "Zadanie 15",
    Title: "Zadanie - 29020",
    Status: "Zakończone",
    Opis: "Naprawa sprzęgła w BMW.",
    Type: "Story",
    Priority: "High",
    Estimate: 2.5,
    Przypisz: "Adam Polak",
  },
  {
    Id: "Zadanie 16",
    Title: "Zadanie - 29021",
    Status: "Zakończone",
    Opis: "opracowanie procedury kontroli jakości naprawy pojazdów.",
    Type: "Others",
    Priority: "Critical",
    Estimate: 1.5,
    Przypisz: "Krzysztof Kwiatkowski",
  },
  {
    Id: "Zadanie 17",
    Title: "Zadanie - 29022",
    Status: "Zakończone",
    Opis: "Spotkanie z pracownikami.",
    Type: "Story",
    Priority: "Critical",
    Estimate: 5.5,
    Przypisz: "Jan Kowalski",
  },
  {
    Id: "Zadanie 18",
    Title: "Zadanie - 29023",
    Status: "Sprawdzane",
    Opis: "Rozliczenie do urzędu skarbowego.",
    Type: "Story",
    Priority: "Critical",
    Estimate: 1,
    Przypisz: "Ewa Sikora",
  },
  {
    Id: "Zadanie 19",
    Title: "Zadanie - 29024",
    Status: "Do sprawdzenia",
    Opis: "Koszty zakupu części zamiennych.",
    Type: "Story",
    Priority: "Normal",
    Estimate: 0.5,
    Przypisz: "Ewa Sikora",
  },
  {
    Id: "Zadanie 20",
    Title: "Zadanie - 29025",
    Status: "Do podjęcia",
    Opis: "Wystawienie faktury dla Jana Kowalskiego.",
    Type: "Improvement",
    Priority: "Low",
    Estimate: 3.5,
    Przypisz: "Anna Nowak",
  },
];
