export const sellColumns = [
  { field: "id", headerName: "ID", width: 70 },
  {
    field: "invoiceNumber",
    headerName: "Numer faktury",
    width: 120,
  },
  {
    field: "sellDate",
    headerName: "Data sprzedaży",
    width: 130,
  },

  {
    field: "clientName",
    headerName: "Nazwa Kontrahenta",
    width: 240,
  },

  {
    field: "brand",
    headerName: "Marka",
    width: 140,
  },

  {
    field: "model",
    headerName: "Model",
    width: 100,
  },

  {
    field: "serialNumber",
    headerName: "Numer VIN",
    width: 230,
  },

  {
    field: "price",
    headerName: "Cena sprzedaży",
    width: 130,
  },

  {
    field: "paymentMethod",
    headerName: "Metoda płatności",
    width: 150,
  },
];

//temporary data
export const sellRows = [
  {
    id: 1,
    invoiceNumber: "FV/AU/1/24",
    sellDate: "04-01-2024",
    clientName: "Jan Kowalski",
    brand: "Opel",
    model: "Astra",
    serialNumber: "W0VBD8EG2K8074466",
    price: "89900",
    paymentMethod: "gotówka",
  },
  {
    id: 2,
    invoiceNumber: "FV/AU/2/24",
    sellDate: "14-01-2024",
    clientName: "Krzysztof Kwiatkowski",
    brand: "Honda",
    model: "Civic",
    serialNumber: "NLAFC1580HW007295",
    price: "105000",
    paymentMethod: "kredyt",
  },
  {
    id: 3,
    invoiceNumber: "FV/AUM/1/24",
    sellDate: "21-01-2024",
    clientName: "Roman Nowak",
    brand: "Peugeot",
    model: "308",
    serialNumber: "VR3UPHNKSMT118717",
    price: "50500",
    paymentMethod: "gotówka",
  },
  {
    id: 4,
    invoiceNumber: "FV/AU/3/24",
    sellDate: "02-02-2024",
    clientName: "FHU Anna Krzyżanowska",
    brand: "Audi",
    model: "A4",
    serialNumber: "WAUZZZF44KA108448",
    price: "124000",
    paymentMethod: "leasing",
  },
  {
    id: 5,
    invoiceNumber: "FV/AUM/2/24",
    sellDate: "12-02-2024",
    clientName: "Karol Szymczak",
    brand: "Mercedes-Benz",
    model: "GLC",
    serialNumber: "WDC2539161V199928",
    price: "145800",
    paymentMethod: "gotówka",
  },
  {
    id: 6,
    invoiceNumber: "FV/AUM/3/24",
    sellDate: "22-02-2024",
    clientName: "Edyta Zając",
    brand: "Skoda",
    model: "Otavia",
    serialNumber: "TMBJG7NE2J0093554",
    price: "48900",
    paymentMethod: "gotówka",
  },
  {
    id: 7,
    invoiceNumber: "FV/AUM/4/24",
    sellDate: "05-03-2024",
    clientName: "Adam Krzeszowski",
    brand: "Honda",
    model: "CR-V",
    serialNumber: "JHMRT5860LX201383",
    price: "155000",
    paymentMethod: "kredyt",
  },
  {
    id: 8,
    invoiceNumber: "FV/AUM/5/24",
    sellDate: "04-04-2024",
    clientName: "Katarzyna Olszewska",
    brand: "Fiat",
    model: "Tipo",
    serialNumber: "ZFACF9C34PU031557",
    price: "103500",
    paymentMethod: "gotówka",
  },
  {
    id: 9,
    invoiceNumber: "FV/AU/4/24",
    sellDate: "24-04-2024",
    clientName: "JR Jacek Ratajczak",
    brand: "Citroen",
    model: "C5 Aircross",
    serialNumber: "VR7A4DGZSNL022163",
    price: "163200",
    paymentMethod: "leasing",
  },
  {
    id: 10,
    invoiceNumber: "FV/AUM/6/24",
    sellDate: "14-05-2024",
    clientName: "Arkadiusz Bąk",
    brand: "BMW",
    model: "318",
    serialNumber: "WBA3K11060K461474",
    price: "89500",
    paymentMethod: "gotówka",
  },
  {
    id: 11,
    invoiceNumber: "FV/AUM/7/24",
    sellDate: "26-05-2024",
    clientName: "Zenon Masłak",
    brand: "Toyota",
    model: "Yaris",
    serialNumber: "JTMRW3FV90D087805",
    price: "61500",
    paymentMethod: "gotówka",
  },
];
